### ISSUE TITLE
[FeatureRequest] Any plan to support generate dart code?

### ISSUE THREAD

**Issue by AnnatarHe** [dotansimha/graphql-tools-rs#33]
I'm using apollo tools to generate `swift` and `typescript` code, It works very well.
but there are no good enough tools like `apollo tools` to generate `dart` code.
Does this project have any plan to generate other language code?

**Comment by dotansimha** [comment]
Hi there @AnnatarHe , this seems to be the incorrect repo. 
Did you mean to open it in https://github.com/dotansimha/graphql-code-generator?
